### ISSUE TITLE
Can't build 1.4.0

### ISSUE THREAD

**Issue by DamienCassou** [protesilaos/iosevka-comfy#9]
Hi Prot,

I'm [packaging iosevka-comfy for nix](https://github.com/NixOS/nixpkgs/pull/259054) and the last update fails to build:

```
 Executing 8 - Pending 024 (89%) | CPU:100% - RAM:024%× Error Unhandled exception when building "Builtin::File::dist/iosevka-comfy/ttf-unhinted/iosevka-comfy-semilight.ttf":
 Error: Error: Composite {user} cannot be resolved: cv57,6.
    at Composite.decompose (file:///build/source/font-src/support/variant-data.mjs:234:19)
    at Composite.resolve (file:///build/source/font-src/support/variant-data.mjs:249:39)
    at Module.apply (file:///build/source/font-src/support/variant-data.mjs:19:17)
    at createParaImpl (file:///build/source/font-src/index.mjs:62:15)
    at reinit (file:///build/source/font-src/index.mjs:74:16)
    at main (file:///build/source/font-src/index.mjs:24:15)
    at ChildProcess.<anonymous> (/build/source/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Does it ring a bell?

**Comment by protesilaos** [comment]
> From: Damien Cassou ***@***.***>
> Date: Thu,  5 Oct 2023 00:11:03 -0700
>
> Hi Prot,

Hello Damien,

> I'm [packaging iosevka-comfy for nix](https://github.com/NixOS/nixpkgs/pull/259054) and the last update fails to build:
>
> ```
>  Executing 8 - Pending 024 (89%) | CPU:100% - RAM:024%× Error Unhandled exception when building "Builtin::File::dist/iosevka-comfy/ttf-unhinted/iosevka-comfy-semilight.ttf":
>  Error: Error: Composite {user} cannot be resolved: cv57,6.
>     at Composite.decompose (file:///build/source/font-src/support/variant-data.mjs:234:19)
>     at Composite.resolve (file:///build/source/font-src/support/variant-data.mjs:249:39)
>     at Module.apply (file:///build/source/font-src/support/variant-data.mjs:19:17)
>     at createParaImpl (file:///build/source/font-src/index.mjs:62:15)
>     at reinit (file:///build/source/font-src/index.mjs:74:16)
>     at main (file:///build/source/font-src/index.mjs:24:15)
>     at ChildProcess.<anonymous> (/build/source/node_modules/verda/lib/actions/nodejs/command.js:53:31)
>     at ChildProcess.emit (node:events:517:28)
>     at emit (node:internal/child_process:944:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
>
> Does it ring a bell?

It seems that "cv57 = 6" cannnot be resolved.  I am checking the
private-build-plans.toml and cannot find an entry for it.  Maybe it is a
caching issue?

All the best,
Prot

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by DamienCassou** [comment]
I'm closing this and will reopen if the issue happens again. Thank you.
